stages:
  train:
    cmd: python src/train.py --version ${version}
    deps:
      - src/train.py
      - data/raw/df_features.csv
    params:
      - version
    metrics:
      - metrics/metrics.json:
          cache: false
    outs:
      - models/:
          cache: false
          persist: true
